Chat/auth.py
from flask import Blueprint, render_template, flash, redirect, url_for
from Chat.utils import redirect_back
from flask_login import login_user
from Chat.forms import LoginForm, RegistForm
from Chat.models import User
"""
处理登录和注册视图的蓝图
"""
auth = Blueprint("auth", __name__)


@auth.route('/login', methods=["POST", "GET"])
def login():
    from Chat.app import db
    form = LoginForm()
    if form.validate_on_submit():
        username = form.name.data
        password = form.password.data
        if User.query.filter_by(username=username).first() is not None:
            admin = User.query.filter_by(username=username).first()
            if admin.check_pwd(password=password):
                login_user(admin, remember=False)
                admin.is_login = True
                db.session.commit()
                return redirect_back()
            else:
                flash("密码错误!")
        else:
            flash("用户名不存在!")
    return render_template("login.html", form=form)


@auth.route('/regist', methods=["POST", "GET"])
def regist():
    from Chat.app import db
    form = RegistForm()
    if form.validate_on_submit():
        username = form.name.data
        if not User.query.filter_by(username=username).first():
            u = User(username=username)
            u.set_password(form.password1.data)
            db.session.add(u)
            db.session.commit()
            flash("注册成功!")
            return redirect(url_for('login'))
        else:
            flash("该用户名已被使用")
    return render_template("regist.html", form=form)

Chat/templates/Userpage.html
{% extends "index.html"%}
{% from 'bootstrap/form.html ' import render_field %}
{% from 'bootstrap/form.html ' import render_form %}

{% block title%}个人简介{% endblock %}

{% block content %}
<style>
    #info{
        resize:none;
    }
    body{
      margin-top:50px;
    }

</style>
<div class="col-4"></div>
<div class="col-4 text-center mt-5">
    {% if u.face == "default"%}
    <img src="{{avatars.default(size='l')}}" alt="#" class="">
    {% else %}
    <img src="{{url_for('static',filename='user_faces/'+u.face)}}" alt="#" width="256px" height="256px">
    {% endif %}
</div>
<div class="col-4"></div>
<div class="col-4 mt-5"></div>
<div class="col-4 mt-5 text-center">
    {% if u.id == current_user.id %}
    {{render_form(form)}}
    {% else %}
    <ul class="list-group">
        <p class="text-secondary" style="font-size:25px;">用户名</p>
        <li class="list-group-item list-group-item-action"><p class="text-primary">{{u.username}}</p></li>
        <hr>
        <p class="text-secondary" style="font-size:25px;">个人简介</p>
        <li class="list-group-item list-group-item-action"><p class="text-primary">{% if u.info == None%}该用户无简介{% else %}{{u.info}}{% endif %}</p></li>
    </ul>
    {% endif %}
</div>
<div class="col-4 mt-5"></div>

{% endblock %}

{% block script %}
<script>
    $(function(){
        {% if request.args.get("submit") == 1%}
        alert("保存成功！");
        {% endif %}
        {% if u.id != current_user.id%}
        $('.active').removeClass('active');
        {% endif %}
    })

</script>
{% endblock %}

Chat/templates/_anony_more.html
{% for message in messages%}
<div class="col-2"></div>
<div class="col-8" style="margin-bottom:70px;">
    <div id="avatars" class="float-left"><img
            src="{% if message.face == 'default'%}{{avatars.default(size='s')}}{% else %}{{url_for('static',filename='user_faces/'+message.face)}}{% endif %}"
            alt="#" height="48px" width="48px" style="border-radius: 5px;"></div>
    <div id="msg-box" class="float-left ml-2 mb-2"
         style="max-width: 400px;background-color:  #D0D0D0;border-radius:3px ">
        <div id="username" class="ml-3 mr-3 mt-1"><strong>{{message.author}}</strong><small
                class="text-secondary ml-3"
                style="font-size:8px;">&nbsp;{{moment(message.timestamp).format('LLL')}}</small></div>
        <div id="content" class="ml-3 mr-3"><p class="mt-2" style="font-size:20px;">{{message.body|safe}}</p></div>
    </div>
</div>
<div class="col-2"></div>
{% endfor %}

Chat/templates/_message.html
<div class="col-2"></div>
<div class="col-8" style="margin-bottom:70px;">
    <div id="avatars" class="float-left"><img
            src="{% if face == 'default'%}{{avatars.default(size='s')}}{% else %}{{url_for('static',filename='user_faces/'+face)}}{% endif %}"
            alt="#" height="48px" width="48px" style="border-radius: 5px;"></div>
    <div id="msg-box" class="float-left ml-2 mb-2"
         style="max-width: 400px;background-color:  #D0D0D0;border-radius:3px ">
        <div id="username" class="ml-3 mr-3 mt-1"><strong>{{username}}</strong>
            <small class="text-secondary ml-3" style="font-size:8px;">&nbsp;{{moment(m.timestamp).format('LLL')}}
            </small>
        </div>
        <div id="content" class="ml-3 mr-3"><p class="mt-2" style="font-size:20px;">{{content|safe}}</p></div>
    </div>
</div>
<div class="col-2"></div>

Chat/templates/anonymous_room.html
{% extends "index.html"%}
{% from 'bootstrap/form.html ' import render_field %}
{% from 'bootstrap/form.html ' import render_form %}

{% block title%}欢迎进入匿名聊天室{% endblock %}


{% block content %}
<style>
    body{margin-top:50px;
    }
    .room-info{
        position:fixed;
        top:44px;
        left:0px;
        width:250px;
    }

    #room-status p{
        line-height:10px;
    }
    #message-textarea:empty:before{
        content:attr(data-placeholder);
        color:grey;
    }
    #message-textarea:focus:before{
        content:none;
    }




</style>

<div class="modal fade Share-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3>分享房间&nbsp;<strong style="font-size:15px;color:red;">输入下列url即可加入</strong></h3>
                <button class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <input type="text" class="form-control"
                           value="{{url_for('room_bp.anonymous_room',room_id = r.id,_external = True)}}" readonly>
                </div>
            </div>
        </div>
    </div>
</div>
<div style="width:246.5px;height:100%;background-color:#F0F0F0;position:fixed;top:50px;right:0px;">
    <p class="text-warning text-center mt-2" style="font-size:20px;">该房间为匿名聊天室</p>
    <p class="text-danger">1.离开房间后除了聊天记录以外其他所有信息都不会被记录</p>
    <p class="text-danger">2.为保证匿名性，用户一旦离开该页面即视为离开房间</p>
    <div class="text-center">
        <p>您的虚拟信息</p>
        <img src="{{url_for('static',filename='user_faces/'+anony_face)}}" alt="#" width="100px">
        <p class="mt-2">{{anony_name}}</p>
    </div>
</div>

<div class="room-info" style="background-color:#D0D0D0;border-radius:5px;z-index:1;">
    <img src="{% if r.face == 'default'%}{{avatars.default(size='l')}} {% else%} {{url_for('static',filename='room_faces/'+r.face)}}{% endif %}"
         alt="#" width="250px" height="250px">
    <div class="info" style="float:left;">
        <p class="mt-1"><strong>房间名:</strong><span style="font-size:15px;color:red;">{{r.name}}</span></p>
        <p><strong>房间号:</strong><span style="font-size:15px;color:red;">{{r.id}}</span></p>
        <p><strong>房主:</strong><span style="color:red;">&nbsp;{{author.username}}</span></p>
        <p><strong>简介:</strong><span style="color:red;">{{r.info}}</span></p>
        {% if r.create_user_id == current_user.id%}
        <strong>在线人数:</strong><span id="online-count" style="color:red;">0</span>
        {% endif %}
    </div>
    <div style="display:inline-block;" class="mt-2">
        <button class="btn btn-secondary float-left ml-4" data-toggle="modal" data-target=".Share-modal">分享</button>
        <button class="btn btn-danger ml-5" onclick="leave_room('quit');" id="quit">退出房间</button>
        <button  onclick="leave_room('records')" class="btn btn-sm btn-success mt-2 ml-4 mb-2">查找聊天记录</button>
    </div>
</div>
<div style="width:250px;height:130px;position:fixed;top:600px;border:1px solid #D0D0D0;background-color:#F0F0F0;border-radius:3px;overflow:auto;z-index:1;"
     id="room-status" class="ml-3">
</div>
{% for message in messages%}
<div class="col-2"></div>
  <div class="col-8" style="margin-bottom:70px;">
    <div id="avatars" class="float-left"><img src="{% if message.face == 'default'%}{{avatars.default(size='s')}}{% else %}{{url_for('static',filename='user_faces/'+message.face)}}{% endif %}" alt="#" height="48px" width="48px" style="border-radius: 5px;"></div>
    <div id="msg-box" class="float-left ml-2 mb-2" style="height:70px;max-width: 400px;background-color:  #D0D0D0;border-radius:3px ">
      <div id="username" class="ml-3 mr-3 mt-1"><strong>{{message.author}}</strong><small class="text-secondary ml-3" style="font-size:8px;">&nbsp;{{moment(message.timestamp).format('LLL')}}</small></div>
      <div id="content" class="ml-3 mr-3"><p class="mt-2" style="font-size:20px;">{{message.body|safe}}</p></div>
    </div>
  </div>
  <div class="col-2"></div>
{% endfor %}
<div style="position:fixed;left:250px;" class="fixed-bottom">
    <button class="btn btn-primary float-left" id="emoji">表情</button>
    <div contenteditable="true" id="message-textarea" data-placeholder="在这输入消息" class="float-left ml-1"
         style="width:950px;min-height:35px;background-color:#D0D0D0;border:1px solid;resize:none;border:1px solid #D0D0D0;border-radius:3px;"></div>
    <button class="btn btn-secondary mb-3 ml-1" id="send">发送</button>
</div>
{% endblock %}
{% block script%}
<script>
var socket;
$(function(){
    scrollTo(0,document.body.scrollHeight);
    $('#message-textarea').css('width','950px');
    {% if request.args.get("edit")%}
    alert("保存成功!");
    {% elif request.args.get("create")%}
    alert("创建成功!");
    {% else %}
    alert("您已进入房间!");
    {% endif %}

    $("#message-textarea").emoji({
      button:"#emoji",
      showTab: false,
      animation: 'fade',
      icons: [{
        name: "贴吧表情",
        path: "/static/img/tieba/",
        maxNum: 50,
        file: ".png",
      }]
    });

    socket = io("/anonymous");
    var room_id = {{r.id}};
    socket.on('connect',function(){
        socket.emit("join",{{r.id}});
    });
    $('#send').click(function(){
      var $textarea = $('#message-textarea');
      var message = $textarea.html();
      var msg = [message,"{{r.id}}"];
      socket.emit('new message',msg);
      $textarea.html('');

  });
  $(document).keypress(function(e) {

　　if (e.which == 13)
    {
        e.preventDefault();
        $('#send').click();
    }
    });
    //滑到顶部加载更多记录
    var page=1;
    $(window).on('scroll',function(){
	"use strict";
	 var scrolled = $(window).scrollTop();
	 if(scrolled <= 0)
	 {
	    page = page+1;
	    console.log(page);
	    	$.ajax({
	        url:"{{url_for('room_bp.get_more_anony',room_id = r.id)}}",
	        type:"get",
	        success:function(data){
	            console.log(data["total_pages"]);
	            if(data["total_pages"] < page){
	                alert("没有更多记录!");
	            }
	            else{
	                console.log(data["html"]);
	                $('#room-status').after(data["html"]).fadeIn(1000);
	                var moment = $('.flask-moment');
	                $.each(moment,function(index,value){
	                    var v = $(value);
	                    var t = v.text().replace('T',' ');
                        t = t.replace('Z',' ');
                        console.log(t);
                        v.text(t);
                        v.css("display","inline");
	                })
	            }

	        }
	    });
	 }
    });



    socket.on('new message',function(data){
    if (data.error == 1){
        alert(data.message);
        return;
      }
      $('.row').append(data.html);
      var moment = $('.flask-moment');
      $.each(moment,function(index,value){
      var v = $(value);
      if (v.css("display") != "inline"){
      var t = v.text().replace('T',' ');
      t = t.replace('Z',' ');
      v.text(t);
      v.css("display","inline");
      }
      })
      scrollTo(0,document.body.scrollHeight);
    });
    setInterval(function(){
        if($('.emoji_container').css("display") != "none")
        {
            $('.emoji_container').css({"position":"fixed","left":"250px","top":"370px","z-index":"1"});

        }
    },100);
    //进入/退出房间监听函数
    socket.on("status",function(data){
        $('#online-count').html(data.count);
        if (data.type == "join" ){
        $("#room-status").append("<p class=\"text-primary\">"+data.html+"</p>");
        }
        else{
        $("#room-status").append("<p class=\"text-secondary\">"+data.html+"</p>");
        }
    });
    $('.nav-link').click(function(){
        alert("请先退出聊天室!");
        return false;
    })
})
function leave_room(argument){
        socket.emit("leave",{{r.id}},function(){
            socket.disconnect();
            if(argument == "quit"){
            window.location.href = "{{url_for('main.index',quit = 1)}}";
            }
            else{
            window.location.href = "{{url_for('room_bp.chat_records',room_id = r.id,anony = 1)}}";
            }
    });
    }


</script>
{% endblock %}

Chat/templates/chat_page.html
{% extends "index.html"%}

{% block title%}欢迎进入匿名聊天室{% endblock %}


{% block content %}
<style>
    body{margin-top:50px;}
    .room-info{
        position:fixed;
        top:44px;
        left:0px;
        width:250px;
    }
    #message-textarea{
            width:950px;
            min-height:35px;
            background-color:#D0D0D0;
            border:1px solid;
            resize:none;
            border:1px solid #D0D0D0;
            border-radius:3px;
    }
    #room-status p{
        line-height:10px;
    }
    #message-textarea:empty:before{
        content:attr(data-placeholder);
        color:grey;
    }
    #message-textarea:focus:before{
        content:none;
    }





</style>

<div class="modal fade Share-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3>分享房间&nbsp;<strong style="font-size:15px;color:red;">输入下列url即可加入</strong></h3>
                <button class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <input type="text" class="form-control"
                           value="{{url_for('room_bp.chat_page',room_id = r.id,_external = True)}}" readonly>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="room-info" style="background-color:#D0D0D0;border-radius:5px;z-index:1;">
    <img src="{% if r.face == 'default'%}{{avatars.default(size='l')}} {% else%} {{url_for('static',filename='room_faces/'+r.face)}}{% endif %}"
         alt="#" width="250px" height="250px">
    <div class="info" style="float:left;">
        <p class="mt-1"><strong>房间名:</strong><span style="font-size:15px;color:red;">{{r.name}}</span></p>
        <p><strong>房间号:</strong><span style="font-size:15px;color:red;">{{r.id}}</span></p>
        <p><strong>房主:</strong><span style="color:red;">&nbsp;{{author.username}}</span></p>
        <p><strong>简介:</strong><span style="color:red;">{{r.info}}</span></p>
        {% if r.create_user_id == current_user.id%}
        <strong>在线人数:</strong><span id="online-count" style="color:red;">0</span>
        {% endif %}
    </div>
    <div style="display:inline-block;" class="mt-2">
        <button class="btn btn-secondary float-left ml-4" data-toggle="modal" data-target=".Share-modal">分享</button>
         <button class="btn btn-danger ml-5" onclick="leave_room('quit');" id="quit">退出房间</button>
         <button  onclick="leave_room('records')" class="btn btn-sm btn-success mt-2 ml-4 mb-2">查找聊天记录</button>
    </div>
</div>
<div style="width:250px;height:130px;position:fixed;top:575px;border:1px solid #D0D0D0;background-color:#F0F0F0;border-radius:3px;z-index:1" id="room-status" class="ml-3">
</div>
{% for message in messages%}

<div class="col-2"></div>
  <div class="col-8" style="margin-bottom:70px;">
    <div id="avatars" class="float-left"><img src="{% if message.author.face == 'default'%}{{avatars.default(size='s')}}{% else %}{{url_for('static',filename='user_faces/'+message.author.face)}}{% endif %}" alt="#" height="48px" width="48px" style="border-radius: 5px;"></div>
    <div id="msg-box" class="float-left ml-2 mb-2" style="max-width: 400px;background-color:  #D0D0D0;border-radius:3px ">
      <div id="username" class="ml-3 mr-3 mt-1"><strong>{{message.author.username}}</strong><small class="text-secondary ml-3" style="font-size:8px;">&nbsp;{{moment(message.timestamp).format('LLL')}}</small></div>
      <div id="content" class="ml-3 mr-3"><p class="mt-2" style="font-size:20px;">{{message.body|safe}}</p></div>
    </div>
  </div>
  <div class="col-2"></div>

{% endfor %}
<div style="position:fixed;left:250px;" class="fixed-bottom">
     <button class="btn btn-primary float-left" id="emoji">表情</button>
    <div contenteditable="true" id="message-textarea" data-placeholder="在这输入消息" class="float-left"></div>
    <button class="btn btn-secondary float-left mb-2 ml-1" id="send">发送</button>
</div>


{% endblock %}
{% block script%}
<script>
var socket
$(function(){
    scrollTo(0,document.body.scrollHeight);
    {% if edit == 1 %}
    alert("保存成功!");
    {% elif request.args.get("create")%}
    alert("创建成功!");
    {% else %}
    alert("您已进入房间!");
    {% endif %}

    //emoji表情包
    $("#message-textarea").emoji({
      button:"#emoji",
      showTab: false,
      animation: 'fade',
      icons: [{
        name: "贴吧表情",
        path: "../static/img/tieba/",
        maxNum: 50,
        file: ".png"
      }]
    });
    //创建socket对象
    socket = io();
    //连接事件
    socket.on('connect',function(){
        console.log("connect");
        socket.emit("join",{{r.id}});
    });
    $('#send').click(function(){
      var $textarea = $('#message-textarea');
      var message = $textarea.html();
      var msg = [message,"{{r.id}}","{{current_user.username}}"];
      socket.emit('new message',msg);
      $textarea.html('');

  });
  $(document).keypress(function(e) {

　　if (e.which == 13)
    {
        e.preventDefault();
        $('#send').click();
    }
    });

    var page=1;
    $(window).on('scroll',function(){
	"use strict";
	 var scrolled = $(window).scrollTop();
	 if(scrolled <= 0 && document.body.scrollHeight > 800)
	 {
	    page = page+1;
	    console.log(page);
	    	$.ajax({
	        url:"{{url_for('room_bp.get_more',room_id = r.id)}}",
	        type:"get",
	        success:function(data){
	            console.log(data["total_pages"]);
	            if(data["total_pages"] < page){
	                alert("没有更多记录!");
	            }
	            else{
	                $('#room-status').after(data["html"]).fadeIn(1000);
	                var moment = $('.flask-moment');
	                $.each(moment,function(index,value){
	                    var v = $(value);
	                    var t = v.text().replace('T',' ');
                        t = t.replace('Z',' ');
                        console.log(t);
                        v.text(t);
                        v.css("display","inline");
	                })
	            }

	        }
	    });
	 }
    });
    socket.on('new message',function(data){
      if (data.error == 1){
        alert(data.message);
        return;
      }
      $('.row').append(data.message_html);
      var moment = $('.flask-moment');
      $.each(moment,function(index,value){
      var v = $(value);
      if (v.css("display") != "inline"){
      var t = v.text().replace('T',' ');
      t = t.replace('Z',' ');
      v.text(t);
      v.css("display","inline");
      }
      })
      scrollTo(0,document.body.scrollHeight);
    });
    setInterval(function(){
        if($('.emoji_container').css("display") != "none")
        {
            $('.emoji_container').css({"position":"fixed","left":"250px","top":"370px","z-index":"1"});
        }
    },500);
    //进入/退出房间监听函数
    socket.on("status",function(data){
        //更新房间人数
        $('#online-count').html(data.count);
        if (data.type == "join" ){
        $("#room-status").append("<p class=\"text-primary\">"+data.username+"</a>进入了房间</p>");
        }
        else{
        $("#room-status").append("<p class=\"text-secondary\">"+data.username+"退出了房间</p>");
        }
    });
    $('.user-page').tooltip();
    $('.nav-link').click(function(){
        alert("请先退出聊天室!");
        return false;
    })


})
//退出处理函数
    function leave_room(argument){
        socket.emit("leave",{{r.id}},function(){
            socket.disconnect();
            if (argument == "quit"){
            window.location.href = "{{url_for('main.index',quit = 1)}}";
            }
            else{
            window.location.href ="{{url_for('room_bp.chat_records',room_id = r.id)}}";
            }
    });
    }

</script>
{% endblock %}

Chat/templates/edit_room.html
{% extends "./index.html" %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'bootstrap/form.html ' import render_form %}
{% block title %}
编辑房间信息
{% endblock %}

{% block content%}
<style>body{margin-top:50px;}</style>
<div class="col-12 text-center mt-4">
    <div class="page-header"><h1 class="mb-3 text-primary mt-3">编辑房间信息</h1></div>
</div>
<div class="col-3"></div>
<div class="col-6 text-center">
    <hr>
    {% if r.face == 'default' %}
    <img src="{{avatars.default(size='l')}}" alt="#">
    {% else %}
    <img src="{{url_for('static',filename='room_faces/'+r.face)}}" alt="#" width="250px" height="250px">
    {% endif %}
    <hr>
</div>
<div class="col-3"></div>
<div class="col-3"></div>
<div class="col-6">
    {{render_form(form)}}
    <hr>
</div>
<div class="col-3"></div>
{% endblock %}

Chat/templates/home.html
{% extends "index.html"%}
{% from 'bootstrap/form.html ' import render_form %}

{% block title%}首页{% endblock %}


{% block content %}
<style>body{margin-top:50px;}</style>
<div class="col-2"></div>
<div class="col-md-8 text-center mt-lg-4">
    <div class="jumbotron mt-5">
        <h1 class="text-secondary">欢迎来到匿名聊天室</h1>
        <p class="float-left text-primary">搜索房间url并加入</p>
        <div class="text-center">
            {{render_form(form,button_map={"submit":"primary"})}}
        </div>
        <div>
            <form action="{{url_for('user_bp.check_room')}}">
                <button class="btn btn-lg btn-success float-right mr-1">查看房间&rarr;</button>
            </form>
        </div>
        <div>
            <form action="{{url_for('user_bp.create_room')}}">
                <button class="btn btn-success btn-lg float-left ml-1">&larr;创建房间</button>
            </form>
        </div>

    </div>
</div>
<div class="col-2"></div>

<div class="col-md-4">

</div>
<div class="col-md-4"></div>
<div class="col-md-4">

</div>

{% endblock %}
{% block script %}
<script>
    $(function(){
        $('#url').attr("placeholder","在这输入url...");
        $('#submit').addClass("btn-lg");
    })


</script>
{% endblock %}

Chat/templates/index.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static',filename='css/jquery.mCustomScrollbar.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/jquery.emoji.css')}}">
    <title>{% block title %}{% endblock %}</title>
    {{bootstrap.load_css()}}
</head>
<body>
<div class="row">
    <div class="col-12">
        <nav class="navbar navbar-dark navbar-expand-md bg-dark fixed-top">
            <a href="#" class="navbar-brand">Chat</a>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{{url_for('main.index')}}"
                       class="{% if request.endpoint == 'main.index'%} active {% endif %}nav-link">首页</a>
                </li>
                {% if not current_user.is_authenticated %}
                <li>
                <a href="{{url_for('auth.login')}}"
                   class="{% if request.endpoint == 'auth.login'%} active {% endif %}nav-link">登录</a>
                </li>
                <li class="nav-item">
                    <a href="{{url_for('auth.regist')}}"
                       class="{% if request.endpoint == 'auth.regist'%} active {% endif %}nav-link">注册</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a href="{{url_for('user_bp.user_page',user_id = current_user.id)}}"
                       class="{% if request.endpoint == 'user_bp.user_page'%} active {% endif %}nav-link">个人</a>
                </li>
                <li class="nav-item">
                    <a href="{{url_for('user_bp.my_rooms')}}"
                       class="{% if request.endpoint == 'user_bp.my_rooms'%} active {% endif %}nav-link">我的聊天室</a>
                </li>
                <li class="nav-item">
                    <a href="{{url_for('user_bp.create_room')}}"
                       class="{% if request.endpoint == 'user_bp.create_room'%} active {% endif %}nav-link">创建房间</a>
                </li>
                <li class="nav-item">
                    <a href="{{url_for('user_bp.check_room')}}"
                       class="{% if request.endpoint == 'user_bp.check_room'%} active {% endif %}nav-link">查看房间</a>
                </li>
                <li class="nav-item">
                    <a href="{{url_for('room_bp.logout')}}"
                       class="nav-link">登出</a>
                </li>
                {% endif %}
            </ul>
            </nav>

    </div>
    {% if get_flashed_messages()%}
        <div class="col-12">
            {% for message in get_flashed_messages()[:1]%}
            <div class="alert alert-primary" role="alert">
                <button class="close" data-dismiss="alert" id="close-alert">&times;</button>
                {{message}}
            </div>
            {% endfor %}

        </div>
    {% endif %}
    {% block content %}{% endblock %}
</div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->

{{bootstrap.load_js()}}
<script src="http://cdn.bootcss.com/jquery/1.11.3/jquery.js"></script>
{{moment.include_moment(sri=False)}}
{{moment.locale('zh-cn')}}
<script src="{{url_for('static',filename='js/jquery.mousewheel-3.0.6.min.js')}}"></script>
<script src="{{url_for('static',filename='js/jquery.mCustomScrollbar.min.js')}}"></script>
<script src="{{url_for('static',filename='js/jquery.emoji.js')}}"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
<script crossorigin="anonymous" integrity="sha384-nBK38bnVsoQvGdJGVtKno9hHFpl07bff81Db7PBpo7qN1KEA8b46Mm9dJSuf78bh" src="https://lib.baomitu.com/socket.io/2.3.0/socket.io.dev.js"></script>
{% block script %}{% endblock %}
</body>
</html>